package minechem.reference;

import cpw.mods.fml.common.ModMetadata;
import java.util.Arrays;

/*
 * A compendium of all constants for the mod, such as the modID and
 * ResourceLocations, as well as more general things like color codes
 */
public class Compendium
{
	private static final String modPrefix = Compendium.Naming.id + ":";

	public static final class Naming
	{
		public static final String id = "minechem";
		public static final String name = "Minechem";
	}

	public static final class Version
	{
		public static final String major = "@MAJOR@";
		public static final String minor = "@MINOR@";
		public static final String build = "@BUILD@";
		public static final String full = major + "." + minor + "." + build;
	}

	public static final class MetaData
	{
		/**
		 * Setup mod metadata
		 *
		 * @param metadata
		 * @return edited metadata object
		 */
		public static ModMetadata init(ModMetadata metadata)
		{
			metadata.modId = Compendium.Naming.id;
			metadata.name = Compendium.Naming.name;
			metadata.description = Compendium.Naming.name + " is a mod about chemistry, allowing you to research blocks and items, and then break them down into their base compounds and elements.";
			metadata.url = "http://www.minechemmod.com/";
			metadata.logoFile = "assets/" + Compendium.Naming.id + "/logo.png";
			metadata.version = Compendium.Version.major + "." + Compendium.Version.minor + "." + Compendium.Version.build;
			metadata.authorList = Arrays.asList("pixlepix", "jakimfett", "maxwolf");
			metadata.credits = "View a full list of contributors on our site!";
			metadata.autogenerated = false;
			return metadata;
		}
	}

	public static final class Texture
	{

		public static final class IIcon
		{

		}

		public static final class Icon
		{

		}

		public static final class GUI
		{

		}

		public static final class Model
		{

		}
	}

	public static final class Resource
	{
		public static final class Icon
		{

		}

		public static final class GUI
		{

		}

		public static final class Model
		{

		}

		public static final class Tab
		{

		}
	}

	public static final class Config
	{
		public static final String configPrefix = "config/minechem/";
		public static final String assetPrefix = "/assets/minechem/";
		public static final String elementsDataJson = "elementData.json";
		public static final String elementsDataJsonSource = "data/elementsData.json";
	}

	public static final class Color
	{

		public static final String black = "\u00A70";
		public static final String darkBlue = "\u00A71";
		public static final String darkCyan = "\u00A73";
		public static final String darkGreen = "\u00A72";
		public static final String darkGrey = "\u00A78";
		public static final String darkRed = "\u00A74";
		public static final String lightBlue = "\u00A79";
		public static final String lightCyan = "\u00A7b";
		public static final String lightGreen = "\u00A7a";
		public static final String lightGrey = "\u00A77";
		public static final String lightRed = "\u00A7c";
		public static final String orange = "\u00A76";
		public static final String pink = "\u00A7d";
		public static final String purple = "\u00A75";
		public static final String white = "\u00A7f";
		public static final String yellow = "\u00A7e";

	}
}
