var molecules =
[
["cellulose","Cellulose","C<sub>6</sub>H<sub>10</sub>O<sub>5</sub>"],
["water","Water","H<sub>2</sub>O"],
["carbonDioxide","Carbon Dioxide","CO<sub>2</sub>"],
["nitrogenDioxide","Nitrogen Dioxide","NO<sub>2</sub>"],
["toluene","Toluene","C<sub>7</sub>H<sub>8</sub>"],
["potassiumNitrate","Potassium Nitrate","KNO<sub>3</sub>"],
["tnt","Trinitrotoluene","C<sub>6</sub>H<sub>2</sub>(NO<sub>2</sub>)<sub>3</sub>C<sub>7</sub>H<sub>8</sub>"],
["siliconDioxide","Silicon Dioxide","SiO<sub>2</sub>"],
["calcite","Calcite","CaCO<sub>3</sub>"],
["pyrite","Pyrite","FeS<sub>2</sub>"],
["nepheline","Nepheline","AlSiO<sub>4</sub>"],
["sulfate","Sulfate (ion)","SO<sub>4</sub>"],
["noselite","Noselite","Na<sub>8</sub>(AlSiO<sub>4</sub>)<sub>6</sub>SO<sub>4</sub>"],
["sodalite","Sodalite","Na<sub>8</sub>(AlSiO<sub>4</sub>)<sub>6</sub>Cl<sub>2</sub>"],
["nitrate","Nitrate (ion)","NO<sub>3</sub>"],
["carbonate","Carbonate (ion)","CO<sub>3</sub>"],
["cyanide","Potassium Cyanide","KCN"],
["phosphate","Phosphate (ion)","PO<sub>4</sub>"],
["acetate","Acetate (ion)","C<sub>2</sub>H<sub>3</sub>O<sub>2</sub>"],
["chromate","Chromate (ion)","CrO<sub>4</sub>"],
["hydroxide","Hydroxide (ion)","OH"],
["ammonium","Ammonium (ion)","NH<sub>4</sub>"],
["hydronium","Hydronium (ion)","H<sub>3</sub>O"],
["peroxide","Peroxide (ion)","O<sub>2</sub>"],
["calciumOxide","Calcium Oxide","CaO"],
["calciumCarbonate","Calcium Carbonate","CaCO<sub>3</sub>"],
["magnesiumCarbonate","Magnesium Carbonate","MgCO<sub>3</sub>"],
["lazurite","Lazurite","Na<sub>8</sub>AlSiO<sub>4</sub>SO<sub>4</sub>"],
["isoprene","Isoprene","C<sub>5</sub>H<sub>8</sub>"],
["butene","Butene","C<sub>4</sub>H<sub>8</sub>"],
["polyisobutylene","Polyisobutylene Rubber","(C<sub>4</sub>H<sub>8</sub>)<sub>16</sub>C<sub>5</sub>H<sub>8</sub>"],
["malicAcid","Malic Acid","C<sub>4</sub>H<sub>6</sub>O<sub>5</sub>"],
["vinylChloride","Vinyl Chloride Monomer","C<sub>2</sub>H<sub>3</sub>Cl"],
["polyvinylChloride","Polyvinyl Chloride","(C<sub>2</sub>H<sub>3</sub>Cl)<sub>64</sub>"],
["methamphetamine","Methamphetamine","C<sub>10</sub>H<sub>15</sub>N"],
["psilocybin","Psilocybin","C<sub>12</sub>H<sub>17</sub>N<sub>2</sub>O<sub>4</sub>P"],
["iron<sub>3</sub>oxide","Iron (III) Oxide","Fe<sub>2</sub>O<sub>3</sub>"],
["strontiumNitrate","Strontium Nitrate","Sr(NO<sub>3</sub>)<sub>2</sub>"],
["magnetite","Magnetite","Fe<sub>3</sub>O<sub>4</sub>"],
["magnesiumOxide","Magnesium Oxide","MgO"],
["cucurbitacin","Cucurbitacin","C<sub>30</sub>H<sub>42</sub>O<sub>7</sub>"],
["asparticAcid","Aspartic Acid","C<sub>4</sub>H<sub>7</sub>NO<sub>4</sub>"],
["hydroxylapatite","Hydroxylapatite","Ca<sub>5</sub>(PO<sub>4</sub>)<sub>3</sub>OH"],
["alinine","Alanine","C<sub>3</sub>H<sub>7</sub>NO<sub>2</sub>"],
["glycine","Glycine","C<sub>2</sub>H<sub>5</sub>NO<sub>2</sub>"],
["serine","Serine","C<sub>3</sub>H<sub>7</sub>NO<sub>3</sub>"],
["mescaline","Mescaline","C<sub>11</sub>H<sub>17</sub>NO<sub>3</sub>"],
["methyl","Methyl (ion)","CH<sub>3</sub>"],
["methylene","Methylene (ion)","CH<sub>2</sub>"],
["memethacrylate","Methyl Methacrylate","(CH<sub>3</sub>)<sub>3</sub>C<sub>2</sub>O<sub>2</sub>"],
["pmma","Poly(methyl methacrylate)","((CH<sub>3</sub>)<sub>3</sub>C<sub>2</sub>O<sub>2</sub>)<sub>3</sub>"],
["redPigment","Cobalt(II) Nitrate","Co(NO<sub>3</sub>)<sub>2</sub>"],
["orangePigment","Potassium Dichromate","K<sub>2</sub>Cr<sub>2</sub>O<sub>7</sub>"],
["yellowPigment","Potassium Chromate","CrK<sub>2</sub>O<sub>4</sub>"],
["limePigment","Nickel(II) Chloride","NiCl<sub>2</sub>"],
["lightbluePigment","Copper(II) Sulfate","CuSO<sub>4</sub>"],
["purplePigment","Potassium Permanganate","KMnO<sub>4</sub>"],
["greenPigment","Zinc Green","CoZnO<sub>2</sub>"],
["blackPigment","Carbon Black","CH<sub>2</sub>O"],
["whitePigment","Titanium Dioxide","TiO<sub>2</sub>"],
["metasilicate","Metasilicate","SiO<sub>3</sub>"],
["beryl","Beryl","Be<sub>3</sub>Al<sub>2</sub>(SiO<sub>3</sub>)<sub>6</sub>"],
["ethanol","Ethyl Alcohol","C<sub>2</sub>H<sub>5</sub>OH"],
["amphetamine","Amphetamine","C<sub>9</sub>H<sub>13</sub>N"],
["theobromine","Theobromine","C<sub>7</sub>H<sub>8</sub>N<sub>4</sub>O<sub>2</sub>"],
["starch","Starch","(C<sub>6</sub>H<sub>10</sub>O<sub>5</sub>)<sub>3</sub>"],
["sucrose","Sucrose","C<sub>12</sub>H<sub>22</sub>O<sub>11</sub>"],
["pantherine","Pantherine","C<sub>4</sub>H<sub>6</sub>N<sub>2</sub>O<sub>2</sub>"],
["aluminiumOxide","Aluminium Oxide","Al<sub>2</sub>O<sub>3</sub>"],
["fullrene","Carbon Nanotubes","C<sub>64</sub>C<sub>64</sub>C<sub>64</sub>C<sub>64</sub>"],
["valine","Valine","C<sub>5</sub>H<sub>11</sub>NO<sub>2</sub>"],
["penicillin","Penicillin","C<sub>16</sub>H<sub>18</sub>N<sub>2</sub>O<sub>4</sub>S"],
["testosterone","Testosterone","C<sub>19</sub>H<sub>28</sub>O<sub>2</sub>"],
["kaolinite","Kaolinite","Al<sub>2</sub>Si<sub>2</sub>O<sub>5</sub>(OH)<sub>4</sub>"],
["fingolimod","Fingolimod","C<sub>19</sub>H<sub>33</sub>NO<sub>2</sub>"],
["arginine","Arginine","C<sub>6</sub>H<sub>14</sub>N<sub>4</sub>O<sub>2</sub>"],
["shikimicAcid","Shikimic Acid","C<sub>7</sub>H<sub>10</sub>O<sub>5</sub>"],
["sulfuricAcid","Sulfuric Acid","H<sub>2</sub>SO<sub>4</sub>"],
["glyphosate","Glyphosate","C<sub>3</sub>H<sub>8</sub>NO<sub>5</sub>P"],
["asprin","Aspirin","C<sub>9</sub>H<sub>8</sub>O<sub>4</sub>"],
["ddt","DDT","C<sub>14</sub>H<sub>9</sub>Cl<sub>5</sub>"],
["dota","DOTA","C<sub>16</sub>H<sub>28</sub>N<sub>4</sub>O<sub>8</sub>"],
["mycotoxin","T-<sub>2</sub> Mycotoxin","C<sub>24</sub>H<sub>34</sub>O<sub>9</sub>"],
["salt","Salt","NaCl"],
["ammonia","Ammonia","NH<sub>3</sub>"],
["nodularin","Nodularin","C<sub>41</sub>H<sub>60</sub>N<sub>8</sub>O<sub>10</sub>"],
["tetrodotoxin","Tetrodotoxin","C<sub>11</sub>H<sub>11</sub>N<sub>3</sub>O<sub>8</sub>"],
["thc","THC","C<sub>21</sub>H<sub>30</sub>O<sub>2</sub>"],
["mt","Methylcyclopentadienyl Manganese Tricarbonyl","C<sub>9</sub>H<sub>7</sub>MnO<sub>3</sub>"],
["buli","Tert-Butyllithium","LiC<sub>4</sub>H<sub>9</sub>"],
["plat","Chloroplatinic Acid","H<sub>2</sub>PtCl<sub>6</sub>"],
["phosgene","Phosgene","COCl<sub>2</sub>"],
["aalc","Allyl Alcohol","C<sub>3</sub>H<sub>5</sub>OH"],
["hist","Diphenhydramine","C<sub>17</sub>H<sub>21</sub>NO"],
["pal<sub>2</sub>","Batrachotoxin","C<sub>31</sub>H<sub>42</sub>N<sub>2</sub>O<sub>6</sub>"],
["retinol","Retinol","C<sub>20</sub>H<sub>29</sub>OH"],
["xylitol","Xylitol","C<sub>5</sub>H<sub>12</sub>O<sub>5</sub>"],
["weedex","Aminocyclopyrachlor","C<sub>8</sub>H<sub>8</sub>ClN<sub>3</sub>O<sub>2</sub>"],
["xanax","Alprazolam","C<sub>17</sub>H<sub>13</sub>ClN<sub>4</sub>"],
["hcl","Hydrogen Chloride","HCl"],
["cocaine","Cocaine","C<sub>17</sub>H<sub>21</sub>NO<sub>4</sub>"],
["cocainehcl","Cocaine Hydrochloride","C<sub>17</sub>H<sub>21</sub>NO<sub>4</sub>HCl"],
["blueorgodye","Guaiazulene","C<sub>15</sub>H<sub>18</sub>"],
["redorgodye","Pelargonidin","C<sub>15</sub>H<sub>11</sub>O<sub>11</sub>"],
["purpleorgodye","Delphinidin","C<sub>15</sub>H<sub>11</sub>O<sub>7</sub>"],
["olivine","Olivine","Fe<sub>2</sub>SiO<sub>4</sub>"],
["metblue","Methylene Blue","C<sub>16</sub>H<sub>18</sub>N<sub>3</sub>SCl"],
["meoh","Methyl Alcohol","CH<sub>3</sub>OH"],
["lcd","Cholesteryl Benzoate","C<sub>34</sub>H<sub>50</sub>O<sub>2</sub>"],
["radchlor","Radium Chloride","RaCl<sub>2</sub>"],
["caulerpenyne","Caulerpenyne","C<sub>21</sub>H<sub>26</sub>O<sub>6</sub>"],
["latropine","Hyoscyamine","C<sub>17</sub>H<sub>23</sub>NO<sub>4</sub>"],
["gallicacid","Gallic Acid","C<sub>7</sub>H<sub>17</sub>O<sub>5</sub>"],
["glucose","Glucose","C<sub>6</sub>H<sub>12</sub>O<sub>6</sub>"],
["tannicacid","Tannic Acid","(C<sub>7</sub>H<sub>17</sub>O<sub>5</sub>)<sub>10</sub>C<sub>6</sub>H<sub>12</sub>O<sub>6</sub>"],
["hperox","Hydrogen Peroxide","H<sub>2</sub>O<sub>2</sub>"],
["galliumarsenide","Gallium Arsenide","GaAs"],
["fibroin","Fibroin","C<sub>2</sub>H<sub>5</sub>NO<sub>2</sub>C<sub>3</sub>H<sub>7</sub>NO<sub>3</sub>C<sub>2</sub>H<sub>5</sub>NO<sub>2</sub>C<sub>3</sub>H<sub>7</sub>NO<sub>2</sub>C<sub>2</sub>H<sub>5</sub>NO<sub>2</sub>C<sub>3</sub>H<sub>7</sub>NO<sub>2</sub>"],
["aluminiumPhosphate","Aluminium Phosphate","AlPO<sub>4</sub>"],
["potassiumOxide","Potassium Oxide","K<sub>2</sub>O"],
["sodiumOxide","Sodium Oxide","Na<sub>2</sub>O"],
["plagioclaseAnorthite","Anorthite","CaAl<sub>2</sub>Si<sub>2</sub>O<sub>8</sub>"],
["plagioclaseAlbite","Albite","NaAl<sub>2</sub>Si<sub>3</sub>O<sub>8</sub>"],
["orthoclase","Orthoclase","KAlSi<sub>3</sub>O<sub>8</sub>"],
["biotite","Biotite","KFe<sub>3</sub>AlSi<sub>3</sub>O<sub>10</sub>F<sub>2</sub>"],
["augite","Augite","NaFeAl<sub>2</sub>O<sub>6</sub>"],
["talc","Talc","Mg<sub>3</sub>Si<sub>4</sub>O<sub>10</sub>"],
["propane","Propane","C<sub>3</sub>H<sub>8</sub>"],
["peridot","Peridot","Mg<sub>2</sub>O<sub>4</sub>Si"],
["topaz","Topaz","Al<sub>2</sub>O<sub>4</sub>F<sub>2</sub>"],
["zoisite","Zoisite","Ca<sub>2</sub>Al<sub>3</sub>Si<sub>3</sub>O<sub>13</sub>H"],
["cysteine","Cysteine","C<sub>3</sub>H<sub>7</sub>NO<sub>2</sub>S"],
["threonine","Threonine","C<sub>4</sub>H<sub>9</sub>NO<sub>3</sub>"],
["lysine","Lysine","C<sub>6</sub>H<sub>14</sub>N<sub>2</sub>O<sub>2</sub>"],
["methionine","Methionine","C<sub>5</sub>H<sub>11</sub>NO<sub>2</sub>S"],
["tyrosine","Tyrosine","C<sub>9</sub>H<sub>11</sub>NO<sub>3</sub>"],
["histidine","Histidine","C<sub>6</sub>H<sub>9</sub>N<sub>3</sub>O<sub>2</sub>"],
["phenylalanine","Phenylalanine","C<sub>9</sub>H<sub>11</sub>NO<sub>2</sub>"],
["glutamine","Glutamine","C<sub>5</sub>H<sub>10</sub>N<sub>2</sub>O<sub>3</sub>"],
["proline","Proline","C<sub>5</sub>H<sub>9</sub>NO<sub>2</sub>"],
["leucine","Leucine","C<sub>6</sub>H<sub>13</sub>NO<sub>2</sub>"],
["tryptophan","Tryptophan","C<sub>11</sub>H<sub>12</sub>N<sub>2</sub>O<sub>2</sub>"],
["aspartate","Aspartate","C<sub>4</sub>H<sub>7</sub>NO<sub>4</sub>"],
["isoleucine","Isoleucine","C<sub>6</sub>H<sub>13</sub>NO<sub>2</sub>"],
["glutamates","Glutamic Acid","C<sub>5</sub>H<sub>9</sub>NO<sub>4</sub>"],
["asparagine","Asparagine","C<sub>4</sub>H<sub>8</sub>N<sub>2</sub>O<sub>3</sub>"],
["keratin","Keratin","C<sub>4</sub>H<sub>9</sub>NO<sub>3</sub>C<sub>3</sub>H<sub>7</sub>NO<sub>2</sub>SC<sub>5</sub>H<sub>9</sub>NO<sub>2</sub>C<sub>4</sub>H<sub>9</sub>NO<sub>3</sub>C<sub>5</sub>H<sub>9</sub>NO<sub>2</sub>C<sub>3</sub>H<sub>7</sub>NO<sub>2</sub>SC<sub>5</sub>H<sub>9</sub>NO<sub>2</sub>"],
];
